### ISSUE TITLE
lib/bridge.glsl is missing

### ISSUE THREAD

**Issue by MAKIO135** [patriciogonzalezvivo/PixelSpiritDeck#3]
As linked from http://editor.pixelspiritdeck.com/, source file for [bridge.glsl](https://github.com/patriciogonzalezvivo/PixelSpiritDeck/blob/master/lib/bridge.glsl) is missing

**Comment by davcri** [comment]
Seems a longstanding issue however I just run this script to create all screenshots:

and I found out that some cards are broken (blank ones in the screenshot below):

```sh
mkdir screenshots

for frag_file in 00-elements/*.frag; do
    base_name=$(basename "$frag_file" .frag)
    output_image="${base_name}.png"
    glslViewer --noncurses --headless "$frag_file" -E screenshot,"screenshots/$output_image"
done
```
  
![image](https://github.com/patriciogonzalezvivo/PixelSpiritDeck/assets/6860637/bc75c314-a15d-4e79-bf62-4e08fea2df51)
